#!/bin/sh
# Copyright (c) 2023 apus-run

# Pre-commit configuration

RESULT=$(make check)
printf "执行检查中...\n"

if [ -n "$RESULT" ]; then
  echo >&2 "[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中"
  exit 1
fi

exit 0
