# Copyright (c) 2023 apus-run

name: Go

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -coverprofile=cover.out -v ./...

      - name: Post Coverage
        uses: codecov/codecov-action@v2