# Copyright (c) 2023 apus-run

name: Integration Test

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: sudo sh ./script/integrate_test.sh